Digital-Clock issue #128
metafy-social/daily-python-scripts pull request #123
Opened 2022-10-04 14:27 UTC by Sourodip20kar

## Description

A simple Digital Clock

## Future Improvements

Fixes #128 

## Mentions

_Mention and tag the people_

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [x] I have added relevant screenshots in my PR

2022-10-04 15:00 UTC, advaita-saha commented
Please link issue

2022-10-04 17:43 UTC, Sourodip20kar commented
https://github.com/metafy-social/daily-python-scripts/issues/128#issue-1396619270

2022-10-04 22:47 UTC, advaita-saha requested changes
Please create a `.py` file for the code
and a separate `readme.md` file

Also please do this inside `scripts/<your_folder_name>/`

2022-10-05 21:02 UTC, bartick approved these changes

2022-10-07 08:26 UTC, merged