Created the GUI Internet Speed Tester
metafy-social/daily-python-scripts pull request #337
Opened 2022-10-10 19:37 UTC by dishant-yadav

## Description
Created the GUI Internet Speed Tester with TKinter Library

Fixes #289 

## Dependencies
[Speed Test](https://github.com/sivel/speedtest-cli)
TKinter

## Future Improvements

Add an image of an speed meter and improve the UI of the app.

## Screenshots of relevant screens

![Screenshot from 2022-10-11 00-57-00](https://user-images.githubusercontent.com/97543666/194939706-644b044e-377b-4104-89ca-209ba8f94b78.png)

## Developer's checklist

- [🗸 ] My PR follows the style guidelines of this project
- [ 🗸] I have performed a self-check on my work

**If changes are made in the code:**

- [🗸 ] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [ 🗸] My changes in code generate no new warnings
- [𐄂 ] My changes are breaking another fix/feature of the project
- [🗸 ] I have added test cases to show that my feature works
- [🗸 ] I have added relevant screenshots in my PR

2022-10-10 19:41 UTC, dishant-yadav commented
@bartick Please review my PR

2022-10-10 20:10 UTC, bartick commented on scripts/Internet Speed Tester/main.py
> +    ping_lab.config(text='Ping : ' + str(46) + " ms")
Your code doesn't serve the purpose of checking the internet speed. These are just constant values

2022-10-10 20:10 UTC, bartick requested changes

2022-10-10 20:10 UTC, bartick commented on scripts/Internet Speed Tester/main.py
> +    ping_lab.config(text='Ping : ' + str(46) + " ms")
Your code doesn't serve the purpose of checking the internet speed. These are just constant values

2022-10-11 16:59 UTC, dishant-yadav commented on scripts/Internet Speed Tester/main.py
> +    ping_lab.config(text='Ping : ' + str(46) + " ms")
Actually I was facing some issues with the **speedtest library**. So to test the app I hard coded the values. 
I am so sorry for that.
@bartick Please review the code now

2022-10-11 17:12 UTC, dishant-yadav commented on scripts/Internet Speed Tester/main.py
> +    ping_lab.config(text='Ping : ' + str(46) + " ms")
![Screenshot from 2022-10-11 22-37-47](https://user-images.githubusercontent.com/97543666/195156294-1b8a40b3-da89-4d0d-9e04-7161793bee99.png)

2022-10-11 19:04 UTC, bartick approved these changes

2022-10-11 19:05 UTC, merged